{
  "formatVersion": "1.1",
  "component": {
    "group": "net.ornithemc",
    "module": "ploceus",
    "version": "1.17.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.5.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "ploceus-1.17.5.jar",
          "url": "ploceus-1.17.5.jar",
          "size": 105386,
          "sha512": "c0ff752c905450bd19c95503214f536f649c8a1117704d91793302d88c9e687cf20fe8c72dffe32914d93a1b39e9ea0dcab8faba7eab48e8cb8c5948a7651d6b",
          "sha256": "78167c47c5e7f4dc98921821ed9c1bc4845adb3c307b891d4598946a72762cba",
          "sha1": "59d397516cf4dfeb63fb60110a2bcebbe1f4ee51",
          "md5": "8c5d0c1545dabd3f56a53b5f69564426"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.vdurmont",
          "module": "semver4j",
          "version": {
            "requires": "3.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "ploceus-1.17.5.jar",
          "url": "ploceus-1.17.5.jar",
          "size": 105386,
          "sha512": "c0ff752c905450bd19c95503214f536f649c8a1117704d91793302d88c9e687cf20fe8c72dffe32914d93a1b39e9ea0dcab8faba7eab48e8cb8c5948a7651d6b",
          "sha256": "78167c47c5e7f4dc98921821ed9c1bc4845adb3c307b891d4598946a72762cba",
          "sha1": "59d397516cf4dfeb63fb60110a2bcebbe1f4ee51",
          "md5": "8c5d0c1545dabd3f56a53b5f69564426"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ploceus-1.17.5-sources.jar",
          "url": "ploceus-1.17.5-sources.jar",
          "size": 42430,
          "sha512": "957a0340e80bc67c422629efe0fbbfb0b9a0457cfde7d16b7523ed4aa503886ef81a8639beae8a1bf1f778bec088e7c64354bcee88961b500ba47a33fdcbf52a",
          "sha256": "ed75fdd2a2544fa844a51dde36fd2e3cb37d83135dbe1b76898c6505a1b43ffa",
          "sha1": "ef6401817ea208cbac491f7cf435b568e057a55d",
          "md5": "6392aa8e8af629df70ea795c263df0ce"
        }
      ]
    }
  ]
}
