name: Build
on:
  push:
    branches:
      - 'exp/**' 
      - 'dev/**'
  workflow_dispatch: 

jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v6
      - uses: gradle/actions/wrapper-validation@v6

      - name: Setup JDK
        uses: actions/setup-java@v5
        with:
          java-version: 21
          distribution: 'temurin'

      - name: Build
        run: ./gradlew build --stacktrace

      - name: Upload Artifact
        uses: actions/upload-artifact@v7.0.1
        with:
          path: build/libs/*
